### ISSUE TITLE
Unsupervised Loss

### ISSUE THREAD

**Issue by erdzl** [tarun005/USSS_ICCV19#5]
Hi,

thank you for your contribution and for releasing your work.

I tried to rerun your model on Cityscape and IDD datasets. What I noticed particularly is that the Unsupervised Loss (US1, US2)  is extremely low in comparison to typical loss. Did you put a weight vector on that Loss or is that a bug? Can you help me to understand this?

Epoch: 50
train loss : 0.7892	
S1: 0.3645 
S2: 0.3907 
US1: 0.0006 
US2:0.0004 
Total: 0.7892
Best epoch :
Val-IoU-CS= 0.2694
Val-IoU-IDD= 0.2173

Thank you
Best wishes

**Comment by tarun005** [comment]
Hi,
We found that the entropy losses make the training unstable. So, it is better to have them low compared to supervised losses, can you also look at the training curve for entropy losses? Optimum values for weights is an open question, please let us know if you see improvements with other weights.
